var ENUMS = {
  "attacktype": ["SEARCHENGINE", "SUSPICIOUS", "HARVESTER",
    "SUSPICIOUSHARVESTER", "COMMENTSPAMMER", "SUSPICIOUSCOMMENTSPAMMER",
    "HARVESTERCOMMENTSPAMMER", "SUSPICIOUSHARVESTERCOMMENTSPAMMER"]
};

module.exports = ENUMS;
